title = "SUSWINRAJ S K | AWS Cloud Practitioner"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Tamil Nadu, India"
favicon = "/favicon.ico"
firstName = "SUSWINRAJ"
lastName = "S K"
phone = ""
showSocializations = true
showContact = true
sections = ["skills","certifications","creations","experience","education"]

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/suswinraj-sk"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
